// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using restauranteCedro.DAL;

namespace restauranteCedro.Migrations
{
    [DbContext(typeof(RestauranteContext))]
    [Migration("20191228174256_DbRestaurante")]
    partial class DbRestaurante
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("restauranteCedro.DAL.Models.Prato", b =>
                {
                    b.Property<int>("IdPrato")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IdRestaurante");

                    b.Property<string>("NomePrato");

                    b.Property<float>("PrecoPrato");

                    b.HasKey("IdPrato");

                    b.HasIndex("IdRestaurante");

                    b.ToTable("Prato");
                });

            modelBuilder.Entity("restauranteCedro.DAL.Models.Restaurante", b =>
                {
                    b.Property<int>("IdRestaurante")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomeRestaurante");

                    b.HasKey("IdRestaurante");

                    b.ToTable("Restaurante");
                });

            modelBuilder.Entity("restauranteCedro.DAL.Models.Prato", b =>
                {
                    b.HasOne("restauranteCedro.DAL.Models.Restaurante", "Restaurante")
                        .WithMany("Pratos")
                        .HasForeignKey("IdRestaurante")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
